version: '3'

services:

  ntopng:
    image: vimagick/ntopng
    command: --community -d /var/lib/ntopng -i wlo1 -r 127.0.0.1:6379@0 -w 0.0.0.0:3000
    volumes:
      - ./data/ntopng:/var/lib/ntopng
    network_mode: host
    restart: unless-stopped

  redis:
    image: redis:alpine
    command: --save 900 1
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
    restart: unless-stopped
    environment:
        redis_host: "${redis_host}"
        redis_port: "${redis_port}"
 
  # nDPI:
  #   image: ndpi
  #   build: ./nDP
  #   container_name: ndpi
  #   volumes: 
  #     - .:/usr/src/app
  #   restart: unless-stopped
  
  influxdb:
    image: influxdb
    ports:
      - "8086:8086"
    volumes:
      - .:/var/lib/influxdb
  chronograf:
    image: chronograf
    command: --influxdb-url=http://influxdb:8086
    ports:
      - "8888:8888"